/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DocumentCreateNestedManyWithoutUsersInput } from "./DocumentCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { FolderCreateNestedManyWithoutUsersInput } from "./FolderCreateNestedManyWithoutUsersInput";
import { PermissionCreateNestedManyWithoutUsersInput } from "./PermissionCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => DocumentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => DocumentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => DocumentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  documents?: DocumentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => FolderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FolderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FolderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  folders?: FolderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => PermissionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PermissionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PermissionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  permissions?: PermissionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
